ovski_website:
    resource: "@OvskiWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

ovski_mine_stats:
    resource: "@OvskiMineStatsBundle/Controller/"
    type:     annotation
    prefix:   /stats