ovski_website:
    resource: "@OvskiWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

ovski_mine_stats:
    resource: "@OvskiMineStatsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/stats