ovski_website:
    resource: "@OvskiWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

ovski_player_stats:
    resource: "@OvskiPlayerStatsBundle/Controller/"
    type:     annotation
    prefix:   /

ovski_faction_stats:
    resource: "@OvskiFactionStatsBundle/Controller/"
    type:     annotation
    prefix:   /