parameters:
#    ovski_news.example.class: Ovski\NewsBundle\Example

services:
#    ovski_news.example:
#        class: %ovski_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
