<?php

namespace Ovski\StatsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KillRepository extends EntityRepository
{
}
