<?php

namespace Ovski\PlayerStatsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    /**
     * Get all players query builder
     *
     * @return DoctrineQueryBuilder
     */
    public function getAllQueryBuilder()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->orderBy('p.kills', 'DESC');

        return $qb;
    }

    /**
     * Get all players query
     *
     * @return DoctrineQuery
     */
    public function getAllQuery()
    {
        $qb = $this->getAllQueryBuilder();

        return is_null($qb) ? $qb : $qb->getQuery();
    }

    /**
     * Get all players
     *
     * @return Collection Players
     */
    public function getAll()
    {
        $q = $this->getAllQuery();

        return is_null($q) ? array() : $q->getResult();
    }
}
